# Week 1 - Rearranging equations and units{#ch:Workshop1}

## Preliminary infomation {#sec:Prelim}

This workshop contains some fundamental materials on both rearranging equations and units. Unfortunately both of these things result in lost marks for a number of candidates either because of carelessness or lack of understanding.

Bad habits in rearranging equations, such as trying to undertake too many steps at once often lead to error, mantras such as 'change the side change the sign' are often an oversimplification and may lead to error.

Values have to have units, without them things make no sense, and in science we cannot assume units on context. Converting between units is equally important and [famously errors can occur](https://www.bbc.co.uk/news/uk-england-tyne-38744307). You should 'work out' your unit in every case, not just assume it is something and writing that down.

In short, show your working clearly, if you do so you *will* make fewer mistakes. Paper doesn't cost much, and if you write on a tablet each new page is free so please space out your work, when learning things annotate your work with useful notes to explain what you have done and why (this will help you revise), and make it clear!

### Rearranging equations

'Change the side change the sign' is often running through peoples' heads as they rearrange equations, however it is only of limited utility as it makes no sense when considering logs or exponentials. More correctly we should think about using reciprical functions on both sides of an equation, for example if I multiply both sides of an equation by the same thing it is mathematically equivalent of doing nothing.

This subtle distinction would 'fix' almost all of the common errors seen in chemistry.



We will meet rearranging equations again in Week \@ref(ch:Workshop2) when we introduce powers, exponents and logs.

### SI base units

Despite cultural tendancies to hold onto older units (such as pounds & ounces, calories, Calories and miles) in science all units are directly derived from the international standard SI system. 

Althought there have been many versions of metric units over the years it became increasingly important to standardise units. The SI system of base units has seven fundamental units (Table \@ref(tab:SIbase)) from which all other units are derived. Recently there has been interest in finding more fundamental ways to describe each of these units (rather than an actual lump (mass) or bar (length) of platinum) whereby [units are described by relation to physical constants](https://www.npl.co.uk/si-units/the-redefinition-of-the-si-units) (such as the speed of light, or Avagadro's constant which define the meter and mole respectively). 

Table: (\#tab:SIbase) The seven base units from which all others are dervied. 

| SI base unit | symbol | quantity symbol (dimension) | quantity |
|:--------:|:--------:|:--------:|:--------:|
| kilogram | kg | M | mass |
| metre | m | L | length |
| second | s | T | time |
| ampere | A | I | electric current |
| kelvin | K | Θ | temperature |
| mole | mol | N |  amount of substance |
| candela | cd | J | luminous intensity|





### SI Derived units

James Clarke Maxwell developed the field of dimensional analysis. Dimensional analysis shows that units have to be consistent in equations.

To add to values in an equation they must have the same unit - so I can't add kJ mol^-1^ to J K^-1^ mol^-1^, nor can I directly add kJ mol^-1^ to J mol^-1^.

When multiplying or dividing values with units then the units combine (by performing the same operation). Velocity is displacment (in m) divided by time (in s), and so the unit of velocity is m s^-1^.

Some 'combined units' have been given their own unique names (Table \@ref(tab:SIderive)), these often make it easier to use the unit (it is a lot easier to say 'volt' than kg m^2^ s^-3^ A^-1^ each time you need to use it). The case of these units (just as with the SI base units) is important, however it should be noted when writing the unit name, even if they are named for a person, that name begins with a lower case letter.

Table: (\#tab:SIderive) Some common named SI derived units used in chemistry. 

| symbol |  SI derived unit | quantity | SI base units| other SI units |
|:--------:|:--------:|:--------:|:--------:|:--------:|
| Hz | hertz | frequency | s^-1^ ||
| N | newton | force | kg m s^-2^ ||
| Pa | pascal | pressure | kg m^-1^ s^-2^ | N m^-2^|
| J | joule | energy | kg m^2^ s^-2^ | N m |
| W | watt | power | kg m^2^ s^-3^ | J s^-1^ |
| C | coulomb | electrical charge | A s | |
| V | volt | electrical potential | kg m^2^ s^-3^ A^-1^ | J C^-1^ |
| F | farad | electrical capacitance | kg^-1^ m^-2^ s^4^ A^2^ | C V^-1^ |
| Ω | ohm | electrical resistance | kg m^2^ s^-3^ A^-2^ | V A^-1^ |
| S | siemens | electrical conductance | kg^-1^ m^-2^ s^3^ A^2^ | A V^-1^ or 1/Ω |

Having said that, Table \@ref(tab:SIderive) contains some common units used in chemistry the units most used in chemistry for concentration, thermodynamics and kinetics are so far not named for anyone and so are usually written in full form. However mol dm^-3^ is often shortend to [M (for molarity)](https://goldbook.iupac.org/terms/view/A00295), this is a unit I use a lot and so in many questions you will see concentrations given as (for example) 0.250 mM or 1.000 M (not the longer 0.250 mmol dm^-3^ or 1.000 mol dm^-3^).

Please note when reporting compound units there should be a space between each unit, so it is J K^-1^ mol^-1^ not JK^-1^mol^-1^. 

Using negative powers is also the correct way to report units (for example J / mol is incorrect, J mol^-1^ is correct), this is for two reasons, one a solidus (the fancy name for divide sign) is a mathematical operator (and these cannot act on units), secondly there is the potential for confusion with using the / in units (for example J/K/mol is actually more properly written as J K^-1^ mol (not J K^-1^ mol^-1^)).


### Other units and conversion factors

There are a number of non-SI base or derived units which are in common usage which are useful to know and be able to convert between. Table \@ref(tab:nonSI) contains a number of useful unit conversions.

Table: (\#tab:nonSI) The relationship between some other common units and the SI system.

| unit | quantity  | SI equivalant |
|:--------:|:--------:|:--------:|
| torr (or mm Hg) | pressure | $\frac{101325}{760}$ Pa |
| atm | pressure | 101325 Pa |
| bar | pressure | 100000 Pa |
| eV | energy | 1.602176634 × 10^-19^ J |
| cal | energy | 4.184 J |
| Cal | energy | 4.184 kJ |
| Å | length | 1 × 10^-10^ m|

There are myriad other units in use, either with  historical or geographic preference, or just for niche purposes (where would we be without olympic swimming pools or London buses). Examples such as the mile, furlong or beard-second are all units of length.

Further, the unit ºC is formally an SI derived unit. The temperature in kelvin is:

<div class="alert alert-info" role="alert">
<span style="color: black;">
\begin{equation*}
T (\textrm{K}) = T (^\circ \textrm{C}) + 273.15
\end{equation*}
</span>
</div>

Just a note to say that this 273.15 K conversion is 'precise' in other words we can consider it to have infinite significant figures, and so if we happen to know temperatures in centigrade to more than two decimal places we do not loose any of these in conversion to kelvin. 

### SI prefixes and standard form

In general lower case prefixes are used for negative powers and upper case prefixes are used for positive powers, however k (kilo) is an obvious exception to this rule. (Other exceptions are da (deca, 10^1^) and h (hecto, 10^2^)).

Table: (\#tab:SIprefix) The more common SI prefixes used in chemistry. 

| SI prefix | SI prefix 'name' | standard form multiplier|
|:--------:|:--------:|:--------:|
| y | yocto  |10^-24^ |
| z | zepto |10^-21^ |
| a | atto | 10^-18^|
| f | femto | 10^-15^|
| p | pico | 10^-12^|
| n | nano | 10^-9^|
| μ | micro | 10^-6^|
| m | milli | 10^-3^|
| c | centi | 10^-2^|
| d | deci | 10^-1^|
| | | |
| k | kilo | 10^3^|

When prefixes are used there is no space between prefix and unit, (so mm (millimeter) not m m (which could be confused for meter meter)). 

There can be some confusion with prefixes and inverse units, for example ns^-1^ is the same unit as 1/ns. This could be more properly written as 10^9^ s^-1^ (and is not in fact 10^-9^ s^-1^).

When there are squares (or cubes) combined with prefixes it is a statement that the prefix is squared (or cubed) as well. So for example 1 cm^2^ is quite literally 1 cm × 1 cm (or 1 × 10^-4^ m^2^).

## Examples

Below the accessible typed examples you will find a video summary and handwritten notes from the video for each example.

### Rearranging $\Delta G = \Delta H - T \Delta S$ to make $T$ the subject

If we start with one of the most important equations in chemistry, the Gibbs' equation:

<div class="alert alert-light" role="alert">
\begin{equation*}
\Delta G = \Delta H - T \Delta S
\end{equation*}
</div>

Here the capital 'delta' ($\Delta$) in each case means 'large change in' and so they cannot be canceled.

If I wanted to rearrange this equation to make $\Delta S$, the entropy change, the subject then:

<div class="alert alert-light" role="alert">

Start by adding $T\Delta S$ to both sides of the equation:
\begin{equation*}
\Delta G + T \Delta S= \Delta H - T \Delta S + T \Delta S
\end{equation*}
on the right hand side $- T \Delta S + T \Delta S=0$ and so cancel.


We can then subtract $\Delta G$ from both sides of the equation:
\begin{equation*}
\Delta G + T \Delta S -\Delta G = \Delta H -\Delta G
\end{equation*}
now the $\Delta G -\Delta G$ on the left hand side of the equation cancel, leaving us with:
\begin{equation*}
T \Delta S = \Delta H -\Delta G
\end{equation*}

Now to cancel the 'T' on the left hand side we need to divide by '$T$' on both sides:

\begin{equation*}
\frac{T \Delta S}{T} = \frac{\Delta H -\Delta G}{T}
\end{equation*}

which leaves us with an equation with $\Delta S$ as the subject:
\begin{equation*}
\Delta S = \frac{\Delta H -\Delta G}{T}
\end{equation*}
</div>

I recognise as show this is extreamly arduous, however it is changing how we think about the problem which is important.

There is a [video of this](https://youtu.be/EKThFzuncTI) as well as a [pdf of the notes](http://workitoutwithapencil.xyz/wp-content/uploads/2021/07/Rearranging-equations-.pdf) from the video. 

### Conversion of mL to L or cm^3^ to dm^3^

One of the most common conversions undertaken in the physical chemistry lab is conversion of mL to L (or more correctly cm^3^ to dm^3^),  and although most people are happy to know 'you just divide by 1000' most haven't thought 'why', nor does everyone get this unit conversion correct.

Both of these examples are shown in a worked video at the end of this section, as is a pdf of the handwritten notes from this video.

#### Conversion of mL to L

We can solve this logially, by first having the assertion that 1 mL = 1 × 10^-3^ L. Therefore when I want to convert mL to L I just multiply by 1 × 10^-3 (which is equivalent to dividing by 1000), or more formally:

<div class="alert alert-light" role="alert">
1 mL = 1 × 10^-3^ L

1 = 1 × 10^-3^ L mL^-1^
</div>

anything may be multiplied by 1 and there be no change and so if I were to want to convert 27.2 mL to L then:

<div class="alert alert-light" role="alert">
27.2 mL × 1 × 10^-3^ L mL^-1^
</div>


we can see that the units of mL and mL^-1^ cancel and we are left with just L and so:

<div class="alert alert-light" role="alert">
27.2 mL = 27.2 × 10^-3^ L
</div>

Writing this as either 27.2 × 10^-3^ L or 0.0272 L are both equivalent and both valid.

#### Conversion of cm^3^ to dm^3^

It will come as no surprise to know that the same process of either multiplying by 1 × 10^-3^ or dividing by 1000 will correctly do this conversion, however knowing that can help justify the process here.

I am going to start with a similar assertion as above:

<div class="alert alert-light" role="alert">
1 cm = 1 × 10^-2^ m
</div>

and so


1 cm^3^ = (1 × 10^-2^)^3^ m^3^ = 1 × 10^-6^ m^3^
</div>
and equivalently

<div class="alert alert-light" role="alert">
1 dm = 1 × 10^-1^ m
</div>

(remember the prefix is raised to the same power as the number) and so:

<div class="alert alert-light" role="alert">
1 dm^3^ = (1 × 10^-1^)^3^ m^3^ = 1 × 10^-3^ m^3^
</div>

for each of these I can make statements where 1 equals something...

<div class="alert alert-light" role="alert">
1  = 1 × 10^-6^ m^3^ cm^-3^

1  = 1 × 10^-3^ m^3^ dm^-3^
</div>

and I can then combine these into a single statement by dividing one by the other:

<div class="alert alert-light" role="alert">
1 = 1 × 10^-6^ m^3^ cm^-3^ / 1 × 10^-3^ m^3^ dm^-3^
</div>

which simplifies (because m^3^ cancels and so do some of the powers of 10) to :

<div class="alert alert-light" role="alert">
1 = 1 × 10^-3^ dm^3^ cm^-3^
</div>

again if we take the example of 27.2 cm^3^ (which is the more formal unit of mL) then:

<div class="alert alert-light" role="alert">
27.2 cm^3^ = 27.2 cm^3^ × 1 × 10^-3^ dm^3^ cm^-3^ = 27.2 × 10^-3^ dm^3^
</div>

Now I have broken both of these down into multiple steps, and it is good to do this until you become more confident in these conversions, but in time you will be able to streamline this process.

[This video](https://www.youtube.com/embed/8T3FmZ5oJ-s) shows me working through both of the above problems. The 'notes' from this video may be found [here](http://workitoutwithapencil.xyz/wp-content/uploads/2021/07/UnitConversions.pdf).

## Summary of concepts learnt
:::info

- When rearranging equations 'do the same thing to both sides'
- Units should be appended anywhere required. There should be a space between number and unit and each part of the unit, for example -28.3 J K^-1^ mol^-1^.
- The unit 'M' is short for mol dm^-3^
- When units with prefixes are raised to a power, both the unit and prefix is raised to that power, so cm^2^ = (10^-2^)^2^ m^2^ = 10^-4^ m^2^ or ns^-1^ = (10^-9^)^-1^ s^-1^ = 10^9^ s^-1^
:::

## Questions {#sec:QuestionsUnits}

### Rearranging equations {#subsec:rearrange}

Answers for these questions are in Section \@ref(subsec:rearrangeans).

For each of the following rearrange to make the specified variable the subject of the equation.

1. $[A]= [A]_0 - kt$, $t$
1. $E = \frac{1}{2}mv^2$, $v$
1. $F = \frac{q_1 q_2}{4 \pi \varepsilon _0 r^2}$, $r$
1. $\frac{1}{[A]}=\frac{1}{[A]_0}+kt$, $[A]_0$
1. $\ln (x_A)=-\frac{\Delta H}{R}(\frac{1}{T_1}-\frac{1}{T_2})$, $T_1$
1. $K_a=\frac{\alpha ^2 c}{1- \alpha}$, $\alpha$

### Unit conversion questions {#subsec:Unitconv}

Answers for these questions are in Section \@ref(subsec:Unitconvans).

1. Convert the following: 
    a. 3.4 µm to mm and m
    a. 270.4 g mol^-1^ to kg mol^-1^ and yg (molecule^-1^)
    a. 23.4 μg dm^−3^ to mg dm^−3^, g m^−3^, and kg m^−3^
    a. 17.5 µHz to Hz
    a. 5796 cm^-1^ to µm^-1^ and m^-1^

***

2. If a box has dimensions 0.234 m x 34.5 cm x 26.8 mm. What is the volume of the box in:
    a.  cm^3^?
    a.  dm^3^?
    a.  m^3^?
    a.  Å^3^?
    
***

3. The Gibbs free energy of a reaction, $\Delta G$ is given by equation \@ref(eq:gibbs).

\begin{equation}
\Delta G = \Delta H - T \Delta S
(\#eq:gibbs)
\end{equation}

Determine the value of $\Delta G$ at 40 ºC when the enthalpy of reaction, $\Delta H$ = -10.235 kJ mol^-1^ and the molar entropy, $\Delta S$ = +34 J K^-1^ mol^-1^




### Determining units of variables in equations {#subsec:detunits}
Answers for these questions are in Section \@ref(subsec:detunitsans).

1. The ideal gas equation is given in equation \@ref(eq:idealgas).

\begin{equation}
pV = n\textrm{R}T
(\#eq:idealgas)
\end{equation}

The units of the variables are:
    $p$ (pressure), Pa (pascals)
    $V$ (volume), m^3^
    $n$ (number of moles), mol
    $T$ (absolute temperature), K

a.  Determine the SI base units of the gas constant, R.

a. Determine the pressure in mmHg of 1.00 mmol of an ideal gas that occupies 1.65 dm^3^ at 25 ºC.

***

2. The famous Einstein equation $E=mc^2$ is more properly written as:

\begin{equation*}
E^2 = p^2 c^2 + m_0^2 c^4
\end{equation*}

Determine the units of the variable $p$.

***

3. At low temperatures ($T$) the molar heat capacity of a material $C_{p, m}$ (J K^-1^ mol^-1^) is given by equation \@ref(eq:lowtempheat).

\begin{equation}
C_{p, m}= a T^3
(\#eq:lowtempheat)
\end{equation}

Determine the units of the constant, a.

***

4. Determine the units of the coulomb constant, $k_e$, in equation \@ref(eq:coulomb), given that r is the separation of two charges, F the force of attraction between the two charges, and $q_x$ is the charge (in coulombs, C) on each of the particles.

\begin{equation}
F = k_e \frac{q_1 q_2}{r^2}
(\#eq:coulomb)
\end{equation}


## Answers {#sec:Answers}
Where available videos of worked examples are shown in hyperlinks with each answer.

### Rearranging equations answers {#subsec:rearrangeans}

1. $t =\frac{[A]_0-[A]}{k}$
1. $v = \sqrt {\frac{2E}{m}}$
1. $r = \sqrt{\frac{q_1 q_2}{4 \pi \varepsilon_0 F }}$
1. $[A]_0=\frac{[A]}{1-[A]kt}$
1. $\frac{\Delta H T_2}{\Delta H - R T \ln {x_A}}$ [Worked answer](https://www.youtube.com/embed/WmryM91dcXE)

1. $\alpha = \frac{-K_a \pm \sqrt{K_a^2 + 4 c K_a}}{2c}$ [Worked answer](https://www.youtube.com/embed/F7em5K2b4to)

### Unit conversion answers {#subsec:Unitconvans}

1. 
    a. 3.4 × 10^-3^ mm;    3.4 × 10^-6^ m
    a. [0.2704 kg mol^-1^; 449.0 yg](https://www.youtube.com/embed/IKM6a3VxWKs)
    a. 23.4 × 10^-3^ mg dm^−3^;    23.4 × 10^-3^ g m^−3^;   and 23.4 × 10^-6^ kg m^−3^
    a. 17.5 × 10^-6^ Hz
    a. 0.5796 µm^-1^ and 5.796 × 10^5^ m^-1^
 
***

2. 
    a. 2.16 × 10^3^ cm^3^
    a. 2.16 dm^3^
    a. 2.16 × 10^-3^ m^3^
    a. 2.16 × 10^27^ Å^3^
    
***

3. -21 kJ mol^-1^ - please note this value is correct to the appropriate sig figs
<div style="text-align: left;">

### Determining units of variables in equations answers {#subsec:detunitsans}
<div style="text-align: left;">

1.
    a. - kg m^2^ s^-2^ K^-1^ mol^-1^ (this is more ususally written as J K^-1^ mol^-1^)
    a. - 11.3 mm Hg (1.50 kPa)

*** 

2. [kg m s^-1^](https://www.youtube.com/embed/3cuSZZF3Z4Y)

***

3. [J K^-4^ mol^-1^](https://www.youtube.com/embed/SECV4uuki3s)

***

4. [kg m^3^ s^-4^ A^-2^](https://www.youtube.com/embed/DsxrbDyCjTU) or N m^2^ C^-2^
