# Week 2 {#ch:Workshop2}

## Preliminary infomation {#sec:Prelim2}

Previously we have learnt about both units and rearranging equations, and in this material we will learn about how these apply to powers, exponents and logarithms. 

The exponential function '$\textrm{e}$, and its reciprical function, the natural log $\ln$ appear a lot in the natural world, and so appear a lot in chemistry. Kinetics, thermodynamics, and even spectroscopy have examples of exponential decay ($1/e$), and so both exponential functions and logs need to be confidently handled.

Powers (such as squares, cubes and even square roots) also appear frequently in chemistry and the rules for manipulating all of these mathematical functions are similar.

### Rules of powers and exponents {#sec:rulespowers}

Powers and exponentials share a common from, in both cases there is a base (b), raised to a power (p), equation \@ref(eq:powers).

\begin{equation}
b^a
(\#eq:powers)
\end{equation}

- in a power function the base (b) varies as the power (p) is fixed, for example:
    + $c_{p,n} = aT^3$
    + $E=mc^2$
    + $\frac{\textrm{d}[A]}{\textrm{d}t}=-k[A]^2$
- in an exponential function the power (p) varies and the base (b) is fixed, for example:
    + $[\textrm{H}^+]=10^{-p\textrm{H}}$
    + $[A]=[A]_0\textrm{e}^{-kt}$
- negative powers are equivalent to one over the equivalent positive power. So:
    + $\textrm{e}^{-x}= 1/\textrm{e}^{x}$
    + $x^2 = 1 / x^{-2}$



When things have a common base then there are 'rules' on how to combine powers. We have essentially been using some of these rules already when we have considered units.


:::info

When multiplying two things which share a common base, you add the powers:

\begin{equation}
m^a \times m^b = m^{a+b}
(\#eq:combpowermult)
\end{equation}

<div style="height: 1px; background-color: #9FC2D3"></div>

When dividing two things that share a common base, you subtract the denominator power from the numerator power:

\begin{equation}
\frac{p^a}{p^b} = p^{a - b}
(\#eq:combpowerdiv)
\end{equation}

<div style="height: 1px; background-color: #9FC2D3"></div>

When raising something with a power to a further power, then the two powers are multiplied:

\begin{equation}
\left(q^a\right)^b =  q^{a\times b}
(\#eq:combpowerraise)
\end{equation}

:::

There are a few other rules to help us understand how to manipulate powers:

:::info
*Anything* raised to the power 0 is equal to 1:

\begin{equation*}
x^0=1
\end{equation*}

or:

\begin{equation*}
\textrm{e}^0=1
\end{equation*}

<div style="height: 1px; background-color: #9FC2D3"></div>

Roots may be expressed as fractional powers:

\begin{equation}
\sqrt[n]{x}=x^{\frac{1}{n}}
(\#eq:fracpower)
\end{equation}

<div style="height: 1px; background-color: #9FC2D3"></div>

When we see negative powers it is the same as the inverse of the positive power.

\begin{equation}
x^{-n}={\frac{1}{x^n}}
(\#eq:negpower)
\end{equation}
:::


### Rules of logs {#sec:rulelog}

Logs are the inverse function of exponents, and can have many bases:

When we use 'natural logs' we use the terminology $\ln$, a natural log is the inverse of '$e$'.

\begin{equation}
x = \ln e^x
(\#eq:natlog)
\end{equation}

Other logs are ususally marked with the *base*, however if no base is indicated it should be considered that this is $\log_{10}$.

\begin{equation}
x = \log_{10} 10^x
(\#eq:10log)
\end{equation}

Just as with combining functions with powers there are a number of rules which help us handle and manipulate logs, these rules are the same no matter the base of the log. When combining logs (these rules are the same regardless of base).

:::info
For adding to logarithms of the same base:

\begin{equation}
\log_x A + \log_x B = \log_x (AB)
(\#eq:logadd)
\end{equation}

<div style="height: 1px; background-color: #9FC2D3"></div>

When subtracting two logarithms of the same base:

\begin{equation}
\log_x A  - \log_x B = \log_x \left(\frac{A}{B}\right)
(\#eq:logsub)
\end{equation}

<div style="height: 1px; background-color: #9FC2D3"></div>

When taking a logarithm of something raised to a power:

\begin{equation}
\log_x (A^n)= n \log_x A
(\#eq:logpower)
\end{equation}
:::

There are occassions where we need to change the base of a log, this for example occurs in the derivation of the Beer-Lambert law where we look at the $\log_{10}$ of the ratio of light intensity, but this comes from a exponential decay of light intensity through the sample $\ln$.

If we want to change the bases of logs (such as in the Beer-Lambert law), there is one final rule of logs.


:::info
When changing the base of a logarithm:

\begin{equation}
log_b A = \frac{\log_x A}{\log_x b}
(\#eq:convpower)
\end{equation}
:::


### Relationship between logs and exponents

As we have seen previously every function has an inverse function, a function that we can use to 'undo' an action. For addition this inverse function is subtraction, for multiplication, division. In the case of exponents the inverse function is a logarithm (to the same base), and reciprically, the inverse function of a log is an exponential.

We will use this later in the course when we look at generating linear $y=mx+c$ plots (Week \@ref(ch:Workshop3)), because exponetial functions are curved when plotted, and so many graphs which are plotted in chemistry have a $\ln$ of a function on the $y$ axis.

### A note on logs, exponentials and units

You cannot take a log of anything with a unit, nor can you take a exponent of anything with a unit, mathematically it makes no sense. However this helps us with our rearrangements, and working out our units.

For example if determining an equilibrium constant, $K$, from knowing the Gibbs' free energy $\Delta G$:

\begin{equation*}
\Delta G = -RT \ln K
\end{equation*}

we will want to rearrange this equation to make K the subject.

\begin{equation*}
K = \textrm{e}^{-\frac{\Delta G}{RT}}
\end{equation*}

I now know that $K$ has no units (this is because it is based on activity, something you will learn in CH10137). I know this because:

- it is only calculated from an exponential function (which has no units) or
- you can't take the $\ln$ of anything with a unit.

The consequence of this is that $\Delta G$ and $RT$ *must* have the same unit.

## Examples {#sec:examples2}

### Determination of units in equation with powers

:::question
The wavenumber of an *infra*-red vibration within a molecule is linked to the bond strength, $k$ and the reduced mass $\mu$ (kg) of the atoms in the bond, Equation \@ref(eq:bondvib). Determine the units of the bond strength $k$. 

\begin{equation}
\bar{\nu}=\frac{1}{2 \pi c}\sqrt{\frac{k}{\mu}}
(\#eq:bondvib)
\end{equation}

Other infomation: $\bar{\nu}$ (m^-1^), c (m s^-1^)
:::


First we need to rearrange this equation to make $k$, the bond strength the subject.

Since k is in the square root the first step is to rearrange the equation such that the square root and its contents are one one side and everything else is on the other. Therefore if we multiply both sides by $2 \pi c$ then:

$2 \bar{\nu} \pi c = \sqrt{\frac{k}{\mu}}$

Now we can square both sides to eliminate the square root (recall indicies a square root can be written as ½ and if I square both sides - or raise both sides to the power two, then we multiply the two indicies which leaves 1).

$(2 \bar{\nu} \pi c)^2 = \frac{k}{\mu}$

Please note, this is exactly the same as $4 \bar{\nu}^2 \pi^2 c^2$.

Finally we can multiply both sides by $\mu$ to leave k as the subject.

$(2 \bar{\nu} \pi c)^2 \mu = k$

Now we have an equation for $k$ we can substitute in the units for all of the other variables. (Numbers are dimensionless.)

(m^-1^)^2^ (m s^-1^)^2^ kg = $k$

Cancelling:

$k$ = kg s^-2^

:::info
The unit of bond strength, $k$,is more usually written as N m^-1^, but this is the same unit we've just determined because as we can see in Table \@ref(tab:SIderive) a N is a kg m s^-2^, so a N m^-1^ = kg s^-2^.
:::

A [video of this example](https://youtu.be/Q5H00hU6-Wk), and [handwritten notes](http://workitoutwithapencil.xyz/wp-content/uploads/2021/07/Determining-units-of-k.pdf) from the video are available.

### Determination of units in equation with exponential

:::question
The Arrhenius equation (equation \@ref(eq:arrhenius)) shows how the rate of a reaction, $k$, depends upon temperature $T$ (in kelvin). The units of $k$ depend upon the order of reaction.

\begin{equation}
k = A e^{-\frac{E_a}{RT}}
(\#eq:arrhenius)
\end{equation}

Determine the units of the pre-exponential factor $A$ and the activation energy $E_a$ if the reaction is first order, and therefore the units of $k$ are s^-1^.

:::

Here we need to remember that we cannot take an exponential of anything with units, nor does an exponential have units once calculated. Therefore the units of $k$ have to be the same as the units of $A$.

 - Units of $A$ = s^-1^.
 
 We can also say that since the units of $E_a$ have to cancel with the units of RT, then since the units of the gas constant, $R$ are J K^-1^ mol^-1^, and the unit of temperature is K, then:
 
 - Units of $E_a$ = J K^-1^ mol^-1^ × K = J mol^-1^

### Rearranging equations with exponentials.

:::question

Rearrange the Arrhenius equation (equation \@ref(eq:arrhenius)) to make $E_a$ the subject.

:::

As has been previously mentioned $A$ will have the same unit as $k$, and since we cannot take the $\ln$ of anything with a unit we need to have some careful rearranging.

If I start be dividing both sides by $A$, then:

$\frac{k}{A}=e^{-\frac{E_a}{RT}}$

Now $\frac{k}{A}$ is dimensionless and I can take the natural logarithm of both sides (as the reciprical function of e):

$\ln\frac{k}{A}=-\frac{E_a}{RT}$

To get rid of the minus sign (-) I can use the fact that $\ln\frac{k}{A}=-\ln\frac{A}{k}$ (this is an application of rule \@ref(eq:logpower) where n = -1)

$\ln\frac{A}{k}=\frac{E_a}{RT}$

Now we can multiply both sides by $RT$ to leave $E_a$ as the subject of the equation:

$RT \ln\frac{A}{k}=E_a$

A [video of this example](https://youtu.be/55Cqx42kIrY), and [handwritten notes](http://workitoutwithapencil.xyz/wp-content/uploads/2021/07/Rearranging-the-Arrhenius-equation.pdf) from the video are available.

### Solving problems using simultaneous equations.

:::question

The reaction between molecular hydrogen and molecular iodine to produce hydrogen iodide occurs with a rate constant, $k$ of 4.45 × 10^-5^ dm^3^ mol^-1^ s^-1^ and 1.37 × 10^-4^ dm^3^ mol^-1^ s^-1^ at 283 ºC and 302 ºC respectively.

Using the Arrhenius equation (equation \@ref(eq:arrhenius)), determine the pre-exponential factor, $A$, and activation energy, $E_a$ for this reaction.
:::

In the Arrhenius equation there are two unknowns, $E_a$ and $A$. So we need to find a way to determine both of these values. We can do this with simultaneous equations:

Method for solving problem:

- determine an expression using simultaneous equations which eliminates one of the unknowns
- solve for the remaining variable
- substitute this back into the original equation to determine the remaining unknown

If we start with equation \@ref(eq:arrhenius), we can start to rearrange:

\begin{equation*}
k = A e^{-\frac{E_a}{RT}}
\end{equation*}

\begin{equation*}
\frac{k}{A}=e^{-\frac{E_a}{RT}}
\end{equation*}

Then taking the natural log of both sides:

\begin{equation*}
\ln \frac{k}{A}= -\frac{E_a}{RT}
\end{equation*}

Now we can use one of our 'rules of logs', (equation \@ref(eq:logsub)):

\begin{equation*}
\ln {k} - \ln {A}= -\frac{E_a}{RT}
\end{equation*}


From here we can set up the simultaneous equations, having two versions of this equation:

\begin{equation*}
\ln {k_1} - \ln {A}= -\frac{E_a}{RT_1} \tag{Eq1} \\ 
\end{equation*}

\begin{equation*}
\ln {k_2} - \ln {A}= -\frac{E_a}{RT_2} \tag{Eq2}
\end{equation*}

Now if we have Eq1 - Eq2, then:

\begin{equation*}
\ln {k_1} - \ln {A} - \ln {k_2} + \ln {A}= -\frac{E_a}{RT_1} + \frac{E_a}{RT_2}
\end{equation*}

and we can eliminate the $\ln A$ term.

\begin{equation*}
\ln {k_1} - \ln {k_2} = -\frac{E_a}{RT_1} + \frac{E_a}{RT_2}
\end{equation*}

From here we can rearrange to make $E_a$ the subject, firstly by separating the common $\frac{E_a}{R}$ term:

\begin{equation*}
\ln {k_1} - \ln {k_2} = -\frac{E_a}{R} \left(\frac{1}{T_1} + \frac{1}{T_2} \right)
\end{equation*}

then collating the temperature terms and putting them over a common denominator:

\begin{equation*}
\ln {k_1} - \ln {k_2} = -\frac{E_a}{R} \left(\frac{T_2-T_1}{T_1 T_2}  \right)
\end{equation*}

To eliminate the minus sign we can use one of 'rules of logs':

\begin{equation*}
\ln {k_2} - \ln {k_1} = \frac{E_a}{R} \left(\frac{T_2-T_1}{T_1 T_2}  \right)
\end{equation*}

and tidy up the logs:

\begin{equation*}
\ln {\frac{k_2}{k_1}} = \frac{E_a}{R} \left(\frac{T_2-T_1}{T_1 T_2}  \right)
\end{equation*}


Now we can multiply both sides by $R\left(\frac{T_1 T_2}{T_2 - T_1}\right)$ to leave $E_a$ as the subject:

\begin{equation*}
R\left(\frac{T_1 T_2}{T_2 - T_1}\right)\ln {\frac{k_2}{k_1}} = E_a
\end{equation*}

Now we can substitute in our known values for $T_1$, $T_2$, $k_1$ and $k_2$. We firstly need to remember that whenever doing any mathematical calculations with temperature they must be in kelvin!

$T_1$ = 283 ºC = 556 K, $k_1$ = 4.45 × 10^-5^ dm^3^ mol^-1^ s^-1^
$T_2$ = 302 ºC = 575 K, $k_2$ = 1.37 × 10^-4^ dm^3^ mol^-1^ s^-1^

\begin{equation*}
E_a = 8.31446 \textrm{ J K}^{-1} \textrm{ mol}^{-1}\left(\frac{556\textrm{ K } \times 575\textrm{ K}}{575\textrm{ K } - 556\textrm{ K}}\right)\ln {\frac{1.37 \times 10^{-4} \textrm{ dm}^3 \textrm{ mol}^{-1} \textrm{ s}^{-1}}{4.45 \times 10^{-5} \textrm{ dm}^3 \textrm{ mol}^{-1} \textrm{ s}^{-1}}}
\end{equation*}

Therefore:

\begin{equation*}
E_a = 157 \textrm{ kJ mol}^{-1}
\end{equation*}

Now we have found a value for $E_a$ that leaves us with just one unknown, $A$. We can use either Eq1 or Eq2 to solve for this.

\begin{equation*}
\ln {k_1} - \ln {A}= -\frac{E_a}{RT_1} 
\end{equation*}

Rearranging to make $\ln A$ the subject:

\begin{equation*}
\ln {A}= \ln {k_1} + \frac{E_a}{RT_1} 
\end{equation*}

Substituting in our known values of $E_a$, $k_1$ and $T_1$:

\begin{equation*}
\ln {A}= \ln {4.45 \times 10^{-5}} + \frac{157 \times 10^3\textrm{ J mol}^{-1}}{8.31446 \textrm{ J K}^{-1} \textrm{ mol}^{-1} \times 556 \textrm{ K}} 
\end{equation*}

*A note on units - you will of course note that I have written the value of $k_1$ without units in the above equation, this is because in effect the unit was 'lost' in the rearrangement (you can't take the log of anything with a unit), we do have to remember that $A$ has to have the same unit as $k_1$ in order for this cancelling to occur*

\begin{equation*}
\ln {A}= 24.0
\end{equation*}

Therefore:

\begin{equation*}
A= \textrm{e}^{24.0} = 2.7 \times 10^{10} \textrm{ dm}^3 \textrm{ mol}^{-1} \textrm{ s}^{-1}
\end{equation*}

*A note on significant figures - remember when taking an exponent you loose 1 sig fig*.

A [video solving the simultaneous equation](https://youtu.be/hrwBXtnWVAA) and [determining the preexponential factor](https://youtu.be/608WX_mLfBI), and [handwritten notes](http://workitoutwithapencil.xyz/wp-content/uploads/2021/07/Solving-problems-using-simultaneous-equations-2.pdf) from the video are available.

## Summary of concepts learnt {#sec:summary2}
:::info

Logarithms are the reciprical function of exponents:

\begin{equation*}
x = \ln \textrm{e}^x
\end{equation*}

\begin{equation*}
x = \log 10^x
\end{equation*}


<div style="height: 1px; background-color: #9FC2D3"></div>

Exponentials and logarithms may be combined using the following rules:

\begin{equation}
m^a \times m^b = m^{a+b}
(\#eq:combpowermult)
\end{equation}

\begin{equation}
\frac{p^a}{p^b} = p^{a - b}
(\#eq:combpowerdiv)
\end{equation}

\begin{equation}
\left(q^a\right)^b =  q^{a\times b}
(\#eq:combpowerraise)
\end{equation}

<div style="height: 1px; background-color: #9FC2D3"></div>

\begin{equation}
\log_x A + \log_x B = \log_x (AB)
(\#eq:logadd)
\end{equation}

\begin{equation}
\log_x A  - \log_x B = \log_x \left(\frac{A}{B}\right)
(\#eq:logsub)
\end{equation}

\begin{equation}
\log_x (A^n)= n \log_x A
(\#eq:logpower)
\end{equation}

<div style="height: 1px; background-color: #9FC2D3"></div>

- Anything raised to a power 0 is 1.
- Roots may be expressed as fractional powers
- Negative powers indicate one over the equivalent positive power, x^-3^ ≡ 1/x^3^

:::


## Questions {#sec:Questions2}

### Simple log practice {#sec:logpractice}
Answers for these questions are in Section \@ref(subsec:logpracticeans).

Evaluate the following expressions:

1. $\log_{10} 10^6$
1. $\log_{10} 10^{-5}$
1. $\log_{10} (5^4 \times 3^{-2})$
1. $\ln {\pi 6^2}$
1. $e^{\log_e x}=\ln y$


### Rearranging equations {#sec:logrearrange}

Answers for these questions are in Section \@ref(subsec:logrearrangeans)

1. Rearrange the following to make the highlighted term the subject:
    a. $\Delta S = k_B \ln W$, $W$
    a. $\Delta S = nR \ln \frac{V_f}{V_i}$, $V_f$
    a. $\nu =\frac{1}{2 \pi} \left(\frac{k}{\mu}\right)^\frac{1}{2}$, $\mu$
    a. $\ln K = \frac{nFE}{RT}$, $E$
    a. $\ln K'- \ln K = \frac{\Delta H}{R}\left(\frac{1}{T}-\frac{1}{T'}\right)$, $\Delta H$


***

2. The integrated rate equation for a first order reaction is $[A]=[A]_0 e^{-kt}$. 
    a. Rearrange this equation in order to make $k$ the subject.
    a. What units must k have?
    


### pH question. {#sec:pH}

Answers for these questions are in Section \@ref(subsec:pHans)

HCl fully dissociates in water. If 5 cm^3^ (measured using a glass pipette) of 38% w/w HCl solution ($\rho$ = 1.189 kg dm^−3^) is 'added to 20 cm^3^ water'made up' in a 25 cm^3^ standard flask.

a. What is the pH of the resulting solution?
a. What mass of NaOH is required to neutralise the resulting solution?

*Hint: w/w means weight-weight, i.e. the number of g in 100 g. In this case 38 g of HCl in 100 g total of mixture.*

*Hint: you will need to think about units and rearranging equations from Week \@ref(ch:Workshop1).*

### pK~a~ question. {#sec:pKa}

Answers for these questions are in Section \@ref(subsec:pKaans)

The degree of dissociation of an acid, $\alpha$ is related to the acid dissociation constant, $K_a$ and the concentration of the acid, c, as shown in equation \@ref(eq:aciddissociation)

\begin{equation}
K_a=\frac{\alpha ^2 c}{1-\alpha}
(\#eq:aciddissociation)
\end{equation}

Determine the pH of hydrofluoric acid solutions (p$K_a= 3.18$) when the concentration of acid is:

a. 1.00 M
a. 2.50 mM
    
*Hint: We rearranged this equation last week for $\alpha$*    

## Answers {#sec:Answers2}

### Simple log practice answers {#subsec:logpracticeans}

1. 6
1. -5
1. 1.841...
1. 4.728...
1. $x =  \ln y$ [Worked solution](https://www.youtube.com/embed/8ULExqdw4Ko)

### Rearranging equations answers {#subsec:logrearrangeans}


1. Rearrange the following to make the highlighted term the subject:
    a. $W = e^{\frac{\Delta S}{k_B}}$
    a. $V_f=V_i e^{\frac{\Delta S}{nR}}$ [Worked solution](https://www.youtube.com/embed/qRwwTuQ4j8E)
    a. $\mu=\frac{1}{4 \pi^2}\frac{k}{\nu^2}$ [Worked solution](https://www.youtube.com/embed/fBjIQekmxjY)
    a. $E=\frac{RT}{nF}\ln K$
    a. $\Delta H = \left(\frac{TT'}{T'-T}\right)R \ln \frac{K'}{K}$ [Worked solution](https://www.youtube.com/embed/OEoDryg8rdo)

***

2.  a. $k=\frac{\ln [A]_0-\ln [A]}{t}$
    a. s^-1^

### pH answer {#subsec:pHans}

a. pH -0.394
a. $m_{\textrm{NaOH}}=2.5$ g [Worked solution](https://www.youtube.com/embed/dg0o4N8nTxY)


### pK~a~ answer {#subsec:pKaans}

a. Two roots: 0.025 and -0.026 and we can't have a negative degree of dissociation. 
pH 1.6
a. Two roots: 0.40 and -0.66 and we can't have a negative degree of dissociation.
pH 3.0 [Worked solution](https://www.youtube.com/embed/N9YhoXcQxnI)
