# Week 6 {#ch:Workshop6}

## Preliminary infomation {#sec:Prelim6}

Standard anti derivatives (or integrals...)

\begin{equation*}
\begin{array}{cccc}
f^{\prime}(x) \equiv y & & f(x) \equiv \int y ~\textrm{d}x & \textrm{Conditions}\\
  \hline
  \hline
A & & x + C \\ 
Ax^n & & \dfrac{A}{n+1}x^{n+1}+ C & x \neq -1\\ 
\dfrac{A}{x} \equiv A x^{-1} & &  A \ln x + C\\  
\dfrac{A}{Bx+ d} & & \dfrac{A}{B} \ln(Bx + d) +C\\ 
e^{Ax} & &\frac{1}{A} e^{Ax} + C\\
A^x && \frac{A^x}{\ln A} +C\\
A \ln x & & A \left( x \ln x - x \right)+ C\\

\sin Ax & &-\frac{1}{A}\cos Ax + C\\ 
\cos Ax & &\frac{1}{A}\sin Ax + C\\
\tan Ax & &-\frac{1}{A}\ln(\cos Ax) + C \equiv \frac{1}{A}\ln(\sec Ax) + C & -\frac{\pi}{2} < x < \frac{\pi}{2}\\

\frac{A}{x^2 + B^2} && \frac{A}{B}\tan^{-1}\left(\frac{x}{B}\right) + C &B>0\\
Ax^2 e^{Bx} && A\left(\frac{x^2}{B} - \frac{2x}{B^2} + \frac{2}{B^3} \right)e^{Bx} +C\\

v(x) \frac{\textrm{d}u(x)}{\textrm{d}x} && u(x)v(x) - \int u(x)\frac{\textrm{d}v(x)}{\textrm{d}x} +C & \textrm{Integration by Parts}\\

Au + Bv & &A\dfrac{\textrm{d}u}{\textrm{d}x} + B\dfrac{\textrm{d}v}{\textrm{d}x} \\
\end{array}
\end{equation*}


## Questions {#sec:Questions6}

### Basic integration practice

Integrate the following with respect to the variable specified:

1. $f'(x) = \frac{a}{x}$; x
1. $f'(x) = x^\frac{3}{2}+ \frac{x^\frac{1}{2}}{2} - 2x^{-\frac{1}{2}}$, x
1. $f'(b) = \sin (ab)$; b
1. $f'(T) = a + bT + \frac{c}{T}$; T
1. $f'(t) = k$; t
1. $f'([A]) = \frac{1}{[A]}$, [A]
1. $f'([A]) = \frac{1}{[A]^2}$ [A]
1. $f'(t) = -e^{-kt}$, t

### Differential equations

Solve the following differential equations as far as possible:

1. $\frac{\textrm{d}\ln a}{\textrm{d}z}= bz^2$
1. $\frac{\textrm{d}[A]}{\textrm{d}t} = k[A]^2$, when t= 0, [A] = [A]~0~
1. $\frac{\textrm{d}p}{\textrm{d}T}=\frac{\Delta_{p\textrm{vap}}H}{RT^2}$; when T = T~1~, p = p~1~ and when when T = T~2~, p = p~2~
1. $\frac{\textrm{d}[w]}{\textrm{d}V}= -\frac{nRT}{V}$, when V = V~i~, w = 0 and when V = V~f~, w = w

## Answers {#sec:Answers6}

### Basic integration practice

1. $f (x) = a \ln x + C$
1. $f(x) = \frac{2}{5} x^{\frac{5}{2}}+ \frac{x^{\frac{3}{2}}}{3}+4x^{\frac{1}{2}}+C$
1. $f(b) =-\frac{1}{a}\cos (ab) + C$
1. $f(T) = aT + bT^2 + c\ln T + C$
1. $f(t) = kt +C$
1. $f([A])= \ln [A] + C$
1. $f([A])=\frac{1}{[A]}+ C$ 
1. $f(t) = \frac{e^{-kt}}{k}$

### Differential equations

1. $\ln a = \frac{bz^3}{3}+D$
1. $\frac{1}{[A]}=\frac{1}{[A]_0}+ kt$
1. $\ln \frac{p_1}{p_2}=\frac{\Delta_{p\textrm{vap}}H}{R}{\frac{1}{T_2}-\frac{1}{T_1}}$
1. $w = -nRT \ln {V_f}{V_i}$
