--- 
title: "CH10009 Workshop Questions"
author: "Fiona Dickinson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: chemfd/CH10009WorkshopQuestions
description: "Workshop questions for CH10009 Maths"
---
# Welcome {-}

The notes have been prepared in a package called BookDown for RStudio so that the equations are accessible to screen readers. However, by providing the notes as a .html webpage I can also embed short videos to further describe some of the topics. Further you can download the questions and answers, (top left of the screen - down arrow) in a format that suits you (either pdf or epub) to view offline, or change the way this document appears (top left of the screen - A) for ease of reading.

There will be no powerpoint slides or lecture note pdfs provided for this course. All in class time will be spent on workshops, this is your opportunity to get help taylored to the places you need it.

If you [spot any typos](https://docs.google.com/forms/d/1hxCt8XcQ8taLXfymZfl2LUOjHACQ4INnRK6GeArTxsc/edit) or think there are any errors please let me know and I will do my best to fix them.

The recommended text for this course is ['Introduction to Contextual Maths in Chemistry'](https://bath-ac-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=44BAT_ALMA_DS51100784580002761&context=L&vid=44BAT_VU1&lang=en_US&search_scope=CSCOP_44BAT_DEEP&adaptor=Local%20Search%20Engine&tab=local&query=any,contains,contextual%20maths%20in%20chemistry&sortby=rank&pcAvailability=false) by Dickinson (yes me) & McKinley. (Fiona Dickinson and Andrew McKinley. *Introduction to Contextual Maths in Chemistry*. Cambridge: Royal Society of Chemistry, 2021. Print. Chemistry Student Guides ; No. 2.)

## Workshops for CH10009 {-}

The topics for workshops each week are as follows:

- Week \@ref(ch:Workshop1): Rearranging equations, units and standard form
- Week \@ref(ch:Workshop2): Logarithms and exponentials
- Week \@ref(ch:Workshop3): Tables and graphs
- Week \@ref(ch:Workshop4): Calculus - differentiation - the basics and the chain rule
- Week \@ref(ch:Workshop5): Calculus - differentiation - the product rule and partial differentiation
- Week \@ref(ch:Workshop6): Calculus - integration - the basics and definite integrals
- Week \@ref(ch:Workshop7): Some more examples of integration and revision

## Report errors {-}

If you spot any errors or areas of lack of clarity, please message me in Teams or preferably report on the error log below:

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSc83b-C0FsgDr5eQxvT-2NWwEtvOEwYU1WbLE4j53wWfUDIXQ/viewform?embedded=true" width="640" height="1242" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

## Version history {-}

Version 1.1 in progress July 2021.

Version 1.0 complete December 2020.

The initial commit of this book is dated 2nd October 2020.

